version: '3'
services: 
  db:
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports: 
      - "3306:3306"
    volumes: 
      - ./docker/mysql/db:/docker-entrypoint-initdb.d
      - ./docker/mysql/db/mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go_rest_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes: 
      - ./goapp/:/go/src/api
    ports: 
      - "8080:8080"
    depends_on:
      - db
  react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./reactapp/:/usr/src/app
    command: sh -c "npm start"
    ports:
      - 3000:3000